global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: user-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - user-service:8080
        labels:
          application: User-Service

  - job_name: gateway-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - gateway-service:8088
        labels:
          application: Gateway-Service

  - job_name: workspace-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - workspace-service:8082
        labels:
          application: Workspace-Service

  - job_name: admin-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - admin-service:8085
        labels:
          application: Admin-Service

  - job_name: commerce-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - commerce-service:8084
        labels:
          application: Commerce-Service

  - job_name: ingestion-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - ingestion-service:8083
        labels:
          application: ingestion-service

  - job_name: intelligence-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - intelligence-service:8086
        labels:
          application: intelligence-service
