export const AI_CONTEXT_SELECTION_MAX_CHARS = 6000;
export const AI_CONTEXT_AROUND_CURSOR_CHARS = 1000;
export const AI_CONTEXT_EXPLAIN_AROUND_CHARS = 800;
export const AI_CONTEXT_FULL_NOTE_MAX_CHARS = 16000;
export const AI_CONTEXT_NOTE_EXCERPT_MAX_CHARS = 6000;
