export const AI_CONTEXT_SELECTION_MAX_CHARS = 6000;
export const AI_CONTEXT_AROUND_CURSOR_CHARS = 1000;
export const AI_CONTEXT_EXPLAIN_AROUND_CHARS = 800;
export const AI_CONTEXT_FULL_NOTE_MAX_CHARS = 16000;
export const AI_CONTEXT_NOTE_EXCERPT_MAX_CHARS = 6000;
export const AI_CONTEXT_MIN_NOTE_CONTEXT_CHARS = 80;
export const AI_CONTEXT_MIN_CONTINUE_BEFORE_CHARS = 120;
export const AI_CONTEXT_MIN_REWRITE_SELECTED_CHARS = 10;
