# syntax=docker/dockerfile:1.7
FROM node:22-alpine AS build
WORKDIR /app

ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_WORKSPACE_API_BASE_URL
ARG NEXT_PUBLIC_COMMERCE_API_BASE_URL
ARG NEXT_PUBLIC_INGESTION_API_BASE_URL
ARG NEXT_PUBLIC_NOTES_USE_MOCK=false
ARG NEXT_PUBLIC_GRAPH_USE_MOCK=false
ARG NEXT_PUBLIC_GRAPH_CLUSTERS_USE_MOCK=false
ARG API_SERVER_URL=http://gateway-service:8088

ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_WORKSPACE_API_BASE_URL=$NEXT_PUBLIC_WORKSPACE_API_BASE_URL
ENV NEXT_PUBLIC_COMMERCE_API_BASE_URL=$NEXT_PUBLIC_COMMERCE_API_BASE_URL
ENV NEXT_PUBLIC_INGESTION_API_BASE_URL=$NEXT_PUBLIC_INGESTION_API_BASE_URL
ENV NEXT_PUBLIC_NOTES_USE_MOCK=$NEXT_PUBLIC_NOTES_USE_MOCK
ENV NEXT_PUBLIC_GRAPH_USE_MOCK=$NEXT_PUBLIC_GRAPH_USE_MOCK
ENV NEXT_PUBLIC_GRAPH_CLUSTERS_USE_MOCK=$NEXT_PUBLIC_GRAPH_CLUSTERS_USE_MOCK
ENV API_SERVER_URL=$API_SERVER_URL

COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm \
    npm ci

COPY app ./app
COPY components ./components
COPY lib ./lib
COPY next.config.mjs postcss.config.js tailwind.config.js tsconfig.json next-env.d.ts ./
RUN npm run build

FROM node:22-alpine
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

COPY --from=build /app ./

EXPOSE 3000
CMD ["npx", "next", "start", "--hostname", "0.0.0.0", "--port", "3000"]
